name: VM Deploy Translator

on:
  push:
    branches:
      - f25
  pull_request:
    branches:
      - f25
  workflow_dispatch:
    
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_ADMIN }}
          password: ${{ secrets.ADMIN_PASSWORD }}
          script: | 
            cd ${{ secrets.REPO_NAME }}
            git pull origin acee3/implementing-model-translation
            docker compose down
            curl -fsSL https://ollama.com/install.sh | sh
            ollama serve &
            ollama pull gemma3:1b
            docker compose up --build -d
